name: CI
on:
  pull_request:
    branches: ["develop", "main"]
env:
  PYTHON_VERSION: "3.12"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: ./requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linting
        run: ruff check . 
      - name: Check formatting
        run: ruff format --check .
      - name: Run Unit and API Tests
        run: pytest -v
      - name: Run Unit Coverage
        run: pytest --cov=app --cov-report=term-missing --cov-fail-under=94