name: CI
on:
  pull_request:
    branches: ["develop", "main"]
  push:
    tags:
      - "v*"
env:
  PYTHON_VERSION: "3.12"
jobs:
  lint:
    #if: false 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: ./requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linting
        run: ruff check . 
      - name: Check formatting
        run: ruff format --check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit and API Tests
        run: pytest -v

      - name: Run Unit Coverage
        run: pytest --cov=app --cov-report=term-missing --cov-report=xml --cov-fail-under=92
        
  code-quality:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with: 
          fetch-depth: 0
      


  build-push:
    #if: false
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build Docker Image
        run: |
          docker build -t aep-backend:${{ github.run_number }} .
      - name: Docker Login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      - name: Tag and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker tag aep-backend:${{ github.run_number }} $DOCKER_USERNAME/aep-backend:${{ github.run_number }}
          docker push $DOCKER_USERNAME/aep-backend:${{ github.run_number }}
